name: gptui
description: "A new GPTUI project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  dynamic_color: ^1.7.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4

  english_words: ^4.0.0
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/wallpapers/bg1.png
    - assets/wallpapers/bg2.png
    - assets/wallpapers/bg3.png
    - assets/images/avatar.png
    - assets/images/gpt.png
    - assets/images/gemini.png
    - assets/images/meta-llama.png
    - assets/images/microsoft.png
    - assets/images/Qwen.png
    - assets/images/mistralai.png